import Head from "next/head";
import Banner from "../components/Banner/Banner";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
// api end point
import server from "../utils/server";

export default function Home(props) {
  const { genres, movies } = props;

  return (
    <div className="">
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-serif">
        {/* nav */}
        <Header genres={genres} />
        {/* big poster */}
        <Banner movies={movies} />
        {/* list of movies */}
        <Hero movies={movies} />
      </main>
    </div>
  );
}

// getting genres
async function getGenres() {
  const req = await fetch(`https://api.themoviedb.org/3/${server.genres.url}`);
  const data = await req.json();
  return data;
}

// getting trending
async function getTrending() {
  const req = await fetch(`https://api.themoviedb.org/3${server.trending.url}`);
  const data = await req.json();
  return data;
}

// calling above func. here  and getting all the data
export const getServerSideProps = async (context) => {
  // getting our queries -> ?genres=some random number that correspond with a genre
  const genre = context.query.genres;

  let results = await fetch(
    `https://api.themoviedb.org/3${server.results.url}${genre}`
  );

  let movies = await results.json();

  let trending = await getTrending();

  const genres = await getGenres();

  // if we haven't selected a genre movies will default to trending category/genre
  if (!movies.results.length) {
    movies = trending;
  }

  return {
    props: {
      genres,
      movies,
    },
  };
};
