import Head from "next/head";
// api end point
import server from "../utils/server";
import Footer from "../components/Footer/index.js";
import HomePageTemplate from "../Templates/HomePageTemplate.js";

export default function Home(props) {
  return (
    <div className="">
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-serif">
        <HomePageTemplate {...props} />
      </main>
      <Footer />
    </div>
  );
}

export async function fetchMovies() {
  const req = await fetch(`${server.trending.url}`);
  const movie = await req.json();
  return movie;
}
export async function fetchUpcoming() {
  const req = await fetch(`${server.upcoming.url}`);
  const upcoming = await req.json();
  return upcoming;
}
export async function fetchPeople() {
  const req = await fetch(`${server.people.url}`);
  const people = await req.json();
  return people;
}

export const getServerSideProps = async () => {
  const movies = await fetchMovies();
  const upcoming = await fetchUpcoming();
  const people = await fetchPeople();

  return {
    props: {
      movies,
      upcoming,
      people,
    },
  };
};
